name: 'MergeIt'
description: 'Merge a thing'
author: 'Extend'
inputs:
  token:
    required: true
    description: "Github Token"
  context:
    required: true
    description: 'The github context passed as toJson(github)'
  debug:
    required: false
    description: 'Add debug logs to action'
    default: 'false'
  label: # change this
    required: false
    description: 'Label Name to check'
    default: 'MergeMe'
runs:
  using: "node12"
  main: 'dist/index.js'
