name: 'Coalesce'
description: 'Validate and merge a PR'
author: 'Extend'
inputs:
  token:
    required: true
    description: "Github Auth Token"
  context:
    required: true
    description: 'Github context passed as toJson(github)'
  debug:
    required: false
    description: 'Add debug logs to action'
    default: 'false'
  jiraIssue:
    required: true
    description: 'Jira issue to put in merge commit'
  label: # change this
    required: false
    description: 'Label Name to check'
    default: 'MergeMe'
runs:
  using: "node12"
  main: 'dist/index.js'
