name: MergeBot

on:
  pull_request_review:
    types: [submitted, edited]
  pull_request:
    types: [labeled, unlabeled, opened, edited, reopened, sychronize, ready_for_review, submitted]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Log in to Jira
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Find Jira Issue in branch name
        id: findIssue
        uses: atlassian/gajira-find-issue-key@master
        with:
          from: branch
          string: "${{ github.head_ref }}"
      - name: Validate Jira Issue
        run: test -n "${{ steps.findIssue.outputs.issue }}"
      - name: Dump GitHub context
        env:
          DEBUG: true
          JIRA_ISSUE: ${{ steps.findIssue.outputs.issue }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          yarn install
          node script.js
