name: MergeBot

on:
  branch:

  pull_request:
    types: [labeled, unlabeled, opened, edited, reopened, sychronize, ready_for_review]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Dump GitHub context
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          yarn install
          node script.js
